// game.js
// Board/rules engine. Fully deterministic: reduce(state, event) is a pure
// function with no randomness inside it. Any random outcome (die roll, card
// draw) is generated by the acting player's client in a "prepare*" helper and
// baked into the event payload *before* it is applied locally and broadcast,
// so both peers replay the identical event and converge on identical state.

import BoardData from './board-data.js';

export const CARD_TYPES = Object.freeze({
  SHIELD: 'shield',
  SWAP: 'swap',
  DOUBLE_MOVE: 'doubleMove',
});

export const MAX_CARDS = 2;
const CARD_POOL = [CARD_TYPES.SHIELD, CARD_TYPES.SWAP, CARD_TYPES.DOUBLE_MOVE];
const CARD_LABELS = {
  [CARD_TYPES.SHIELD]: 'Shield',
  [CARD_TYPES.SWAP]: 'Swap',
  [CARD_TYPES.DOUBLE_MOVE]: 'Double Move',
};

export const Phase = Object.freeze({
  ROLLING: 'rolling',
  CHOOSE_TOKEN: 'choose-token',
  SHIELD_DECISION: 'shield-decision',
  GAME_OVER: 'game-over',
});

function otherPlayer(player) {
  return player === 'host' ? 'guest' : 'host';
}

export function rollDie() {
  return Math.floor(Math.random() * 6) + 1;
}

function drawRandomCardType() {
  return CARD_POOL[Math.floor(Math.random() * CARD_POOL.length)];
}

// Precomputes the card a landing WOULD draw, if the destination square is a
// card square and the player has room. Safe to call speculatively even when
// a shield decision might change the true final square, because no snake
// head/tail in this board's layout is also a card square.
function computeCardDraw(state, player, square) {
  if (!BoardData.isCardSquare(square)) return null;
  if (state.players[player].cards.length >= MAX_CARDS) return null;
  // Double Move is a dead draw once a token is already locked in at 100 (it
  // can never move again), so it's excluded from the pool for that player —
  // no point handing them a card that does nothing.
  const hasLockedToken = state.players[player].tokens.includes(BoardData.LAST_SQUARE);
  const pool = hasLockedToken ? CARD_POOL.filter((c) => c !== CARD_TYPES.DOUBLE_MOVE) : CARD_POOL;
  return pool[Math.floor(Math.random() * pool.length)];
}

export function createInitialState(hostName, guestName) {
  return {
    players: {
      host: { name: hostName, tokens: [0, 0], cards: [] },
      guest: { name: guestName, tokens: [0, 0], cards: [] },
    },
    turn: 'host',
    phase: Phase.ROLLING,
    lastRoll: null,
    pending: null, // { queue: [{tokenIndex, roll, cardDraw}], player, resolvingIndex? }
    winner: null,
    log: [],
    // Deterministic per-step animation trace for the move currently being
    // resolved — both peers compute the identical sequence from the same
    // event, so it can drive identical walk/ladder/snake/capture/card
    // animations on both screens. Reset to [] each time a new queue starts;
    // moveTraceId bumps alongside so the UI can tell "new move" from
    // "shield decision continuing the same move" apart.
    moveTrace: [],
    moveTraceId: 0,
    startedAt: Date.now(),
    endedAt: null,
    stats: { turns: 0, cardsPlayed: { host: 0, guest: 0 } },
  };
}

function pushLog(state, text) {
  // Keep the full history for the whole game — the log panel/UI decides how
  // much of it to display.
  state.log = [...state.log, { text, ts: Date.now() }];
}

function pushTrace(state, entry) {
  state.moveTrace = [...state.moveTrace, entry];
}

function walkPath(from, dest) {
  const path = [];
  for (let s = from + 1; s <= dest; s++) path.push(s);
  return path;
}

// Whether a token can legally receive this roll (bounds + no self-stack on
// the immediate destination square, per the rules doc).
export function isLegalTokenMove(state, player, tokenIndex, roll) {
  const tokens = state.players[player].tokens;
  const pos = tokens[tokenIndex];
  const dest = pos + roll;
  if (dest > BoardData.LAST_SQUARE) return false;
  const otherIdx = tokenIndex === 0 ? 1 : 0;
  const otherPos = tokens[otherIdx];
  // Square 100 is exempt from the self-stack rule — it's the shared finish
  // line, both of a player's tokens are meant to end up there together to
  // win. Without this exemption, once one token finishes, the other could
  // never land on 100 either (permanently blocked as a "self-stack"),
  // making the match unwinnable.
  if (dest !== 0 && dest === otherPos && dest !== BoardData.LAST_SQUARE) return false;
  return true;
}

export function legalTokenIndices(state, player, roll) {
  return [0, 1].filter((i) => isLegalTokenMove(state, player, i, roll));
}

// A token that has finished (reached square 100) is locked in — it can't be
// captured (handled by BoardData treating 100 as a safe square) and can't be
// swapped away by an opponent's Swap card either.
export function isTokenSwappable(square) {
  return square !== BoardData.LAST_SQUARE;
}

// Pure display helper: where would this token end up if chosen? Resolves
// ladder/snake but not shield (that's an interactive decision made after the
// choice), so a snake preview shows the slide destination as a best guess.
export function previewMove(state, player, tokenIndex, roll) {
  const pos = state.players[player].tokens[tokenIndex];
  const dest = pos + roll;
  const ladder = BoardData.getLadder(dest);
  const snake = BoardData.getSnake(dest);
  let to = dest;
  let type = 'normal';
  if (ladder) {
    to = ladder.to;
    type = 'ladder';
  } else if (snake) {
    to = snake.to;
    type = 'snake';
  }
  return { tokenIndex, from: pos, to, type };
}

// ---- Prepare* helpers: called ONLY by the acting player's client. They may
// use Math.random(); the resulting event is what actually gets applied. ----

export function prepareRollEvent(state, player) {
  return { type: 'ROLL', player, value: rollDie() };
}

export function prepareChooseTokenEvent(state, player, tokenIndex, auto = false) {
  const roll = state.lastRoll;
  const pos = state.players[player].tokens[tokenIndex];
  const dest = pos + roll;
  const cardDraw = computeCardDraw(state, player, dest);
  return {
    type: 'CHOOSE_TOKEN',
    player,
    queue: [{ tokenIndex, roll, cardDraw }],
    auto,
  };
}

export function prepareDoubleMoveEvent(state, player, auto = false) {
  const roll = state.lastRoll;
  const tokens = state.players[player].tokens;
  const queue = [0, 1]
    .filter((i) => tokens[i] + roll <= BoardData.LAST_SQUARE)
    .map((tokenIndex) => {
      const dest = tokens[tokenIndex] + roll;
      return { tokenIndex, roll, cardDraw: computeCardDraw(state, player, dest) };
    });
  return { type: 'PLAY_DOUBLE_MOVE', player, queue, auto };
}

export function prepareSwapEvent(state, player, myTokenIndex, oppTokenIndex) {
  return { type: 'PLAY_SWAP', player, myTokenIndex, oppTokenIndex };
}

export function prepareShieldDecisionEvent(state, player, useShield, auto = false) {
  return { type: 'SHIELD_DECISION', player, useShield, auto };
}

export function prepareForfeitEvent(state, player) {
  return { type: 'FORFEIT_TURN', player };
}

// ---- Pure reducer ----

export function reduce(state, event) {
  switch (event.type) {
    case 'SET_NAME':
      return {
        ...state,
        players: {
          ...state.players,
          [event.player]: { ...state.players[event.player], name: event.name },
        },
      };
    case 'ROLL':
      return applyRoll(state, event);
    case 'CHOOSE_TOKEN':
      return startResolvingQueue(state, event.player, event.queue, event.auto);
    case 'PLAY_DOUBLE_MOVE':
      return applyDoubleMove(state, event);
    case 'PLAY_SWAP':
      return applySwap(state, event);
    case 'SHIELD_DECISION':
      return applyShieldDecision(state, event);
    case 'FORFEIT_TURN':
      return applyForfeitTurn(state, event);
    case 'SYNC_STATE':
      return event.state;
    default:
      return state;
  }
}

function applyRoll(state, event) {
  const next = clone(state);
  next.lastRoll = event.value;
  pushLog(next, `Turn ${next.stats.turns + 1} — ${next.players[event.player].name}`);
  pushLog(next, `${next.players[event.player].name} rolled a ${event.value}.`);
  const legal = legalTokenIndices(next, event.player, event.value);
  if (legal.length === 0) {
    pushLog(next, `${next.players[event.player].name} has no legal move and forfeits the turn.`);
    return endTurn(next);
  }
  next.phase = Phase.CHOOSE_TOKEN;
  return next;
}

// Only takes effect if it's still that player's turn to roll — guards
// against a stale/late forfeit arriving after the player already rolled
// (e.g. they rolled right as the 30s timer expired on their own client).
function applyForfeitTurn(state, event) {
  const next = clone(state);
  if (next.turn !== event.player || next.phase !== Phase.ROLLING) return next;
  pushLog(next, `Turn ${next.stats.turns + 1} — ${next.players[event.player].name}`);
  pushLog(next, `${next.players[event.player].name} ran out of time and forfeits the turn.`);
  return endTurn(next);
}

function applyDoubleMove(state, event) {
  let next = clone(state);
  const player = event.player;
  next.players[player].cards = removeOneCard(next.players[player].cards, CARD_TYPES.DOUBLE_MOVE);
  next.stats.cardsPlayed[player]++;
  pushLog(next, `${next.players[player].name} played Double Move!`);
  if (event.queue.length === 0) {
    pushLog(next, `${next.players[player].name} has no legal move for either token.`);
    return endTurn(next);
  }
  return startResolvingQueue(next, player, event.queue, event.auto);
}

function applySwap(state, event) {
  let next = clone(state);
  const player = event.player;
  const opp = otherPlayer(player);
  pushLog(next, `Turn ${next.stats.turns + 1} — ${next.players[player].name}`);
  next.players[player].cards = removeOneCard(next.players[player].cards, CARD_TYPES.SWAP);
  next.stats.cardsPlayed[player]++;
  const myPos = next.players[player].tokens[event.myTokenIndex];
  const oppPos = next.players[opp].tokens[event.oppTokenIndex];
  // Defensive guard mirroring the UI-level restriction: a finished token
  // (at square 100) is locked in and can't be swapped away. The UI never
  // lets a player create this event, but both peers must still agree on the
  // outcome if it somehow arrives, so the card is spent with no effect.
  if (isTokenSwappable(myPos) && isTokenSwappable(oppPos)) {
    next.players[player].tokens[event.myTokenIndex] = oppPos;
    next.players[opp].tokens[event.oppTokenIndex] = myPos;
    pushLog(next, `${next.players[player].name} played Swap!`);
  } else {
    pushLog(next, `${next.players[player].name}'s Swap had no effect — a finished token can't be swapped.`);
  }
  return endTurn(next);
}

// Starts (or continues) working through a queue of {tokenIndex, roll, cardDraw}
// moves for `player`, pausing in SHIELD_DECISION phase if a move lands on a
// snake while the player holds a shield.
function startResolvingQueue(state, player, queue, auto) {
  let next = clone(state);
  next.pending = { player, queue };
  next.moveTrace = [];
  next.moveTraceId = (state.moveTraceId || 0) + 1;
  if (auto) pushLog(next, `${next.players[player].name} took too long to decide — a random choice was made.`);
  return resolveNextInQueue(next);
}

function resolveNextInQueue(state) {
  let next = clone(state);
  if (!next.pending || next.pending.queue.length === 0) {
    next.pending = null;
    return endTurn(next);
  }
  const { player, queue } = next.pending;
  const [move, ...rest] = queue;
  const tokens = next.players[player].tokens;
  const from = tokens[move.tokenIndex];
  const dest = from + move.roll;
  pushTrace(next, { kind: 'walk', player, tokenIndex: move.tokenIndex, path: walkPath(from, dest) });

  const ladder = BoardData.getLadder(dest);
  if (ladder) {
    tokens[move.tokenIndex] = ladder.to;
    pushTrace(next, { kind: 'ladder', player, tokenIndex: move.tokenIndex, from: dest, to: ladder.to });
    pushLog(next, `${next.players[player].name}: Token ${move.tokenIndex + 1} climbed a ladder ${dest} → ${ladder.to}!`);
    return finishMoveStep(next, player, move.tokenIndex, rest);
  }

  const snake = BoardData.getSnake(dest);
  if (snake) {
    const hasShield = next.players[player].cards.includes(CARD_TYPES.SHIELD);
    if (hasShield) {
      tokens[move.tokenIndex] = dest; // sits at the (safe) snake head while deciding
      next.phase = Phase.SHIELD_DECISION;
      next.pending = {
        player,
        queue: rest,
        shieldChoice: { tokenIndex: move.tokenIndex, tailSquare: snake.to },
      };
      pushLog(next, `${next.players[player].name}: Token ${move.tokenIndex + 1} met a fang at ${dest}! Use Shield?`);
      return next;
    }
    tokens[move.tokenIndex] = snake.to;
    pushTrace(next, { kind: 'snake', player, tokenIndex: move.tokenIndex, from: dest, to: snake.to });
    pushLog(next, `${next.players[player].name}: Token ${move.tokenIndex + 1} was bitten and slid ${dest} → ${snake.to}!`);
    return finishMoveStep(next, player, move.tokenIndex, rest);
  }

  tokens[move.tokenIndex] = dest;
  pushLog(next, `${next.players[player].name}: Token ${move.tokenIndex + 1} moved ${from} → ${dest}.`);
  return finishMoveStep(next, player, move.tokenIndex, rest, move.cardDraw);
}

function finishMoveStep(state, player, tokenIndex, restQueue, cardDraw) {
  let next = clone(state);
  const square = next.players[player].tokens[tokenIndex];

  const capturedIndex = resolveCapture(next, player, square);
  if (capturedIndex !== null) {
    pushTrace(next, {
      kind: 'capture',
      player,
      tokenIndex,
      capturedPlayer: otherPlayer(player),
      capturedIndex,
      at: square,
    });
  }

  if (cardDraw && BoardData.isCardSquare(square)) {
    if (next.players[player].cards.length < MAX_CARDS) {
      next.players[player].cards.push(cardDraw);
      pushTrace(next, { kind: 'card', player, tokenIndex, cardType: cardDraw, at: square });
      pushLog(next, `${next.players[player].name} drew a ${CARD_LABELS[cardDraw]} card!`);
    }
  }

  if (checkWin(next, player)) {
    next.winner = player;
    next.phase = Phase.GAME_OVER;
    next.pending = null;
    next.endedAt = Date.now();
    pushLog(next, `${next.players[player].name} wins!`);
    return next;
  }

  next.pending = { player, queue: restQueue };
  return resolveNextInQueue(next);
}

function applyShieldDecision(state, event) {
  let next = clone(state);
  const pending = next.pending;
  if (!pending || !pending.shieldChoice) return next;
  const { player } = pending;
  const { tokenIndex, tailSquare } = pending.shieldChoice;
  const rest = pending.queue;
  const headSquare = next.players[player].tokens[tokenIndex];

  if (event.auto) pushLog(next, `${next.players[player].name} took too long to decide — a random choice was made.`);

  if (event.useShield) {
    next.players[player].cards = removeOneCard(next.players[player].cards, CARD_TYPES.SHIELD);
    next.stats.cardsPlayed[player]++;
    pushTrace(next, { kind: 'shieldSave', player, tokenIndex, at: headSquare });
    pushLog(next, `${next.players[player].name} used a Shield — Token ${tokenIndex + 1} survived the fang!`);
    next.phase = Phase.CHOOSE_TOKEN;
    return finishMoveStep(next, player, tokenIndex, rest);
  }

  next.players[player].tokens[tokenIndex] = tailSquare;
  pushTrace(next, { kind: 'snake', player, tokenIndex, from: headSquare, to: tailSquare });
  pushLog(next, `${next.players[player].name}: Token ${tokenIndex + 1} slid ${headSquare} → ${tailSquare}.`);
  next.phase = Phase.CHOOSE_TOKEN;
  return finishMoveStep(next, player, tokenIndex, rest);
}

// Returns the captured token index, or null if nothing was captured.
function resolveCapture(state, player, square) {
  if (BoardData.isSafeSquare(square)) return null;
  const opp = otherPlayer(player);
  const oppTokens = state.players[opp].tokens;
  for (let i = 0; i < oppTokens.length; i++) {
    if (oppTokens[i] === square && square !== 0) {
      oppTokens[i] = 0;
      pushLog(state, `${state.players[player].name} captured ${state.players[opp].name}'s token!`);
      return i;
    }
  }
  return null;
}

function checkWin(state, player) {
  const tokens = state.players[player].tokens;
  return tokens[0] === BoardData.LAST_SQUARE && tokens[1] === BoardData.LAST_SQUARE;
}

function endTurn(state) {
  let next = clone(state);
  next.pending = null;
  next.lastRoll = null;
  next.stats.turns++;
  if (next.winner) {
    next.phase = Phase.GAME_OVER;
    return next;
  }
  next.turn = otherPlayer(next.turn);
  next.phase = Phase.ROLLING;
  return next;
}

function removeOneCard(cards, cardType) {
  const idx = cards.indexOf(cardType);
  if (idx === -1) return cards.slice();
  const copy = cards.slice();
  copy.splice(idx, 1);
  return copy;
}

function clone(state) {
  return {
    ...state,
    players: {
      host: { ...state.players.host, tokens: [...state.players.host.tokens], cards: [...state.players.host.cards] },
      guest: { ...state.players.guest, tokens: [...state.players.guest.tokens], cards: [...state.players.guest.cards] },
    },
    log: state.log,
    moveTrace: state.moveTrace,
    stats: { turns: state.stats.turns, cardsPlayed: { ...state.stats.cardsPlayed } },
    pending: state.pending
      ? { ...state.pending, queue: state.pending.queue.map((m) => ({ ...m })), shieldChoice: state.pending.shieldChoice ? { ...state.pending.shieldChoice } : undefined }
      : null,
  };
}
